/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_proandroid_assembly_AssemblyActivity */

#ifndef _Included_com_apress_proandroid_assembly_AssemblyActivity
#define _Included_com_apress_proandroid_assembly_AssemblyActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    getGCD
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_getGCD
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    getGCDAsm
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_getGCDAsm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    convertARGB8888
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_convertARGB8888
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    convertARGB8888Asm
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_convertARGB8888Asm
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    computeAverage8
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_computeAverage8
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    computeAverage8Faster
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_computeAverage8Faster
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    computeAverage8Fastest
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_computeAverage8Fastest
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    computeAverage8Asm
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_computeAverage8Asm
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    runNativeGCDTests
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_runNativeGCDTests
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    runNativeGCDAsmTests
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_runNativeGCDAsmTests
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    runNativeARGB8888Tests
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_runNativeARGB8888Tests
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    runNativeARGB8888AsmTests
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_runNativeARGB8888AsmTests
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    runNativeAverage8Tests
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_runNativeAverage8Tests
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_apress_proandroid_assembly_AssemblyActivity
 * Method:    runNativeAverage8AsmTests
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_apress_proandroid_assembly_AssemblyActivity_runNativeAverage8AsmTests
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
