/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_proandroid_ndk_FibonacciNative */

#ifndef _Included_com_apress_proandroid_ndk_FibonacciNative
#define _Included_com_apress_proandroid_ndk_FibonacciNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_proandroid_ndk_FibonacciNative
 * Method:    recursive
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_apress_proandroid_ndk_FibonacciNative_recursive
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_apress_proandroid_ndk_FibonacciNative
 * Method:    iterativeFaster
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_apress_proandroid_ndk_FibonacciNative_iterativeFaster
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
