/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_apress_proandroid_ndk_Fibonacci */

#ifndef _Included_com_apress_proandroid_ndk_Fibonacci
#define _Included_com_apress_proandroid_ndk_Fibonacci
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_apress_proandroid_ndk_Fibonacci
 * Method:    recursiveNative
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_apress_proandroid_ndk_Fibonacci_recursiveNative
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
